# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

r_github_packages: r-lib/covr

matrix:
  include:
  - r: devel
  - r: release
    after_success: Rscript -e 'covr::codecov()'
    before_cache: Rscript -e 'remotes::install_cran("pkgdown")' -e 'remotes::install_cran("tidyverse")'
    deploy:
      provider: script
      script: Rscript -e 'pkgdown::deploy_site_github()'
      skip_cleanup: true
      on:
        repo: r-lib/fs
        condition: $TRAVIS_BRANCH = master || -n $TRAVIS_TAG
  - r: oldrel
  - r: 3.3
  - r: 3.2
  - r: 3.1
  - name: String Latin-1 locale
    r: release
    before_script:
      - sudo locale-gen en_US
      - export LC_ALL=en_US
